### ISSUE TITLE
Errors stopped working for newer Ember-Data > 2.x

### ISSUE THREAD

**Issue by danshapir** [CrshOverride/ember-web-api#7]
``` javascript
Uncaught Error: Assertion Failed: `InvalidError` expects json-api formatted errors array.
```

Since you've changed what I've done and you return a plain JSON or errors, ember that has moved to JSON-API won't work.

parseErrorResponse is where it happens.

**Comment by CrshOverride** [comment]
@danshapir - I'll make the necessary changes. The last changes I made were to support Ember Data 1.13.15 as a JSON API formatted errors array actually failed in that version. I should be able to push tonight and release a 2.\* compatible version.

**Comment by CrshOverride** [comment]
@danshapir I have a pending PR to address the issue. If at all possible, try installing from the branch and see if:
1. The errors issue is resolved.
2. Nothing else is broken in your application.

I plan on doing the same tomorrow myself.

**Comment by danshapir** [comment]
Good job! I'll try and check it tonight (other time-zone here :) )

**Comment by CrshOverride** [comment]
@danshapir I was able to verify on my own and it looks like errors worked properly and my relationships still loaded as expected. I'm closing this one out for now.

**Comment by danshapir** [comment]
OK great! Didn't get to it...
